apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nodejs-devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "nodejs-app"
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - nodejs-devops
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: nodejs-app
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:3000
