apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: nodejs-canary-analysis
  namespace: nodejs-devops
spec:
  metrics:
    - name: success-rate
      interval: 15s
      count: 3
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (
              sum(
                rate(nodejs_http_requests_total{
                  namespace="nodejs-devops",
                  service="nodejs-rollout-canary",
                  status=~"2.."
                }[1m])
              )
            )
            /
            (
              sum(
                rate(nodejs_http_requests_total{
                  namespace="nodejs-devops",
                  service="nodejs-rollout-canary"
                }[1m])
              )
            )
